name: Tic-Tac-Toe

on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'tictactoe|')
    steps:
      - uses: actions/checkout@v4
      
      - name: Play Tic-Tac-Toe
        uses: marcizhu/readme-tictactoe@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
